language: ruby
cache: bundler
sudo: required
rvm:
  - 2.3
  - 2.4
  - 2.5
notifications:
  email:
    recipients:
      - fhir-testing-list@lists.mitre.org
    on_failure: change
before_install: gem install bundler
